version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/python-ci-cd-demo

permissions:
  - object: /home/ubuntu/python-ci-cd-demo
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 300
      runas: ubuntu

